/**
 * PDF Layout Helpers
 * Shared primitives for drawing branded HiringBrand PDFs
 */

import type { jsPDF } from 'jspdf'

// A4 dimensions in mm
export const PAGE = { w: 210, h: 297, margin: 14 }
export const CONTENT = { x: PAGE.margin, w: PAGE.w - PAGE.margin * 2, top: 38 }

// Design tokens
export const C = {
  teal: '#4ABDAC',
  tealDeep: '#2D8A7C',
  tealLight: '#E8F7F5',
  coral: '#FC4A1A',
  coralLight: '#FFF0EC',
  gold: '#F7B733',
  goldLight: '#FEF9EC',
  slate: '#1E293B',
  slateMid: '#475569',
  slateLight: '#94A3B8',
  surface: '#FFFFFF',
  surfaceDim: '#F1F5F9',
  green: '#059669',
  greenLight: '#ECFDF5',
}

export const FONTS = {
  display: 'Outfit',
  body: 'SourceSans3',
}

// Helper to parse hex to RGB
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '')
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ]
}

export function setColor(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex)
  doc.setTextColor(r, g, b)
}

export function setFill(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex)
  doc.setFillColor(r, g, b)
}

export function setDraw(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex)
  doc.setDrawColor(r, g, b)
}

/**
 * Draw the branded header bar
 */
export function drawHeader(doc: jsPDF, companyName: string, tabTitle: string, scanDate: string) {
  // Teal background bar
  setFill(doc, C.tealDeep)
  doc.rect(0, 0, PAGE.w, 30, 'F')

  // HiringBrand.io logo text
  doc.setFont(FONTS.display, 'bold')
  doc.setFontSize(16)
  setColor(doc, C.surface)
  doc.text('HiringBrand.io', PAGE.margin, 12)

  // Company name
  doc.setFont(FONTS.body, 'normal')
  doc.setFontSize(10)
  doc.text(companyName, PAGE.margin, 20)

  // Tab title — right aligned
  doc.setFont(FONTS.display, 'bold')
  doc.setFontSize(14)
  doc.text(tabTitle, PAGE.w - PAGE.margin, 12, { align: 'right' })

  // Scan date — right aligned
  doc.setFont(FONTS.body, 'normal')
  doc.setFontSize(9)
  doc.text(scanDate, PAGE.w - PAGE.margin, 20, { align: 'right' })

  // Thin accent line below header
  setFill(doc, C.teal)
  doc.rect(0, 30, PAGE.w, 1, 'F')
}

/**
 * Draw the branded footer
 */
export function drawFooter(doc: jsPDF, reportUrl: string) {
  const y = PAGE.h - 10

  // Separator line
  setDraw(doc, C.surfaceDim)
  doc.setLineWidth(0.3)
  doc.line(PAGE.margin, y - 4, PAGE.w - PAGE.margin, y - 4)

  // Left: branding
  doc.setFont(FONTS.body, 'normal')
  doc.setFontSize(7)
  setColor(doc, C.slateLight)
  doc.text('Generated by HiringBrand.io — AI Employer Brand Intelligence', PAGE.margin, y)

  // Right: report URL
  doc.text(reportUrl, PAGE.w - PAGE.margin, y, { align: 'right' })
}

/**
 * Draw a section title with teal accent bar
 */
export function drawSectionTitle(doc: jsPDF, y: number, title: string): number {
  // Teal accent bar
  setFill(doc, C.teal)
  doc.rect(CONTENT.x, y, 3, 5, 'F')

  doc.setFont(FONTS.display, 'bold')
  doc.setFontSize(11)
  setColor(doc, C.slate)
  doc.text(title, CONTENT.x + 7, y + 4)

  return y + 10
}

/**
 * Draw a rounded card background
 */
export function drawCard(doc: jsPDF, x: number, y: number, w: number, h: number, opts?: { fill?: string; border?: string }) {
  const fill = opts?.fill || C.surface
  const border = opts?.border
  const r = 3 // corner radius

  setFill(doc, fill)
  if (border) {
    setDraw(doc, border)
    doc.setLineWidth(0.3)
    doc.roundedRect(x, y, w, h, r, r, 'FD')
  } else {
    doc.roundedRect(x, y, w, h, r, r, 'F')
  }
}

/**
 * Draw a badge (small colored pill)
 */
export function drawBadge(doc: jsPDF, x: number, y: number, text: string, bgColor: string, textColor: string): number {
  const textWidth = doc.getTextWidth(text) + 4
  const height = 5

  setFill(doc, bgColor)
  doc.roundedRect(x, y - 3.5, textWidth, height, 2, 2, 'F')

  doc.setFont(FONTS.body, 'bold')
  doc.setFontSize(7)
  setColor(doc, textColor)
  doc.text(text, x + 2, y)

  return textWidth
}

/**
 * Draw a horizontal sentiment bar
 */
export function drawSentimentBar(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  counts: { strong: number; positive: number; mixed: number; negative: number }
) {
  const total = counts.strong + counts.positive + counts.mixed + counts.negative
  if (total === 0) return

  const colors = {
    strong: C.green,
    positive: C.teal,
    mixed: C.gold,
    negative: C.coral,
  }

  let cx = x
  for (const [key, count] of Object.entries(counts) as Array<[keyof typeof counts, number]>) {
    if (count === 0) continue
    const segW = (count / total) * w
    setFill(doc, colors[key])
    doc.rect(cx, y, segW, h, 'F')
    cx += segW
  }
}

/**
 * Draw sentiment bar legend
 */
export function drawSentimentLegend(
  doc: jsPDF,
  x: number,
  y: number,
  counts: { strong: number; positive: number; mixed: number; negative: number }
) {
  const items = [
    { label: 'Strong', count: counts.strong, color: C.green },
    { label: 'Positive', count: counts.positive, color: C.teal },
    { label: 'Mixed', count: counts.mixed, color: C.gold },
    { label: 'Negative', count: counts.negative, color: C.coral },
  ]

  let cx = x
  for (const item of items) {
    // Color dot
    setFill(doc, item.color)
    doc.circle(cx + 1.5, y - 1, 1.5, 'F')

    // Label
    doc.setFont(FONTS.body, 'normal')
    doc.setFontSize(7)
    setColor(doc, C.slateMid)
    const text = `${item.label} (${item.count})`
    doc.text(text, cx + 5, y)
    cx += doc.getTextWidth(text) + 10
  }
}

/**
 * Wrap text to fit within a max width, returning array of lines
 */
export function wrapText(doc: jsPDF, text: string, maxWidth: number): string[] {
  const words = text.split(' ')
  const lines: string[] = []
  let currentLine = ''

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word
    if (doc.getTextWidth(testLine) > maxWidth && currentLine) {
      lines.push(currentLine)
      currentLine = word
    } else {
      currentLine = testLine
    }
  }
  if (currentLine) lines.push(currentLine)
  return lines
}

/**
 * Draw wrapped text, return the Y position after the last line
 */
export function drawWrappedText(doc: jsPDF, x: number, y: number, text: string, maxWidth: number, lineHeight: number = 4): number {
  const lines = wrapText(doc, text, maxWidth)
  for (const line of lines) {
    doc.text(line, x, y)
    y += lineHeight
  }
  return y
}

/**
 * Truncate text with ellipsis
 */
export function truncate(text: string, max: number): string {
  if (text.length <= max) return text
  return text.slice(0, max - 1) + '…'
}

/**
 * Format date for display
 */
export function formatDate(dateStr: string): string {
  const d = new Date(dateStr)
  return d.toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' })
}

/**
 * Score color helper
 */
export function getScoreColor(score: number): string {
  if (score >= 80) return C.teal
  if (score >= 60) return C.tealDeep
  if (score >= 40) return C.gold
  return C.coral
}

/**
 * Health label helper
 */
export function getHealthLabel(health: string): { text: string; color: string; bgColor: string } {
  switch (health) {
    case 'strong': return { text: 'Well Positioned', color: C.green, bgColor: C.greenLight }
    case 'moderate': return { text: 'Solid Foundation', color: C.gold, bgColor: C.goldLight }
    case 'needs_attention': return { text: 'Growth Opportunity', color: C.gold, bgColor: C.goldLight }
    case 'critical': return { text: 'Significant Opportunity', color: C.coral, bgColor: C.coralLight }
    default: return { text: health, color: C.slateMid, bgColor: C.surfaceDim }
  }
}

export function priorityLabel(p: string): string {
  switch (p) {
    case 'immediate': return 'This Week'
    case 'short_term': return 'This Month'
    case 'long_term': return 'This Quarter'
    default: return p
  }
}

export function effortLabel(e: string): string {
  switch (e) {
    case 'quick_win': return 'Quick Win'
    case 'moderate': return 'Moderate'
    case 'significant': return 'Significant'
    default: return e
  }
}

export function priorityColor(p: string): string {
  switch (p) {
    case 'immediate': return C.coral
    case 'short_term': return C.gold
    case 'long_term': return C.teal
    default: return C.slateMid
  }
}

export const dimensionLabels: Record<string, string> = {
  compensation: 'Compensation',
  culture: 'Culture',
  growth: 'Growth',
  balance: 'Work-Life Balance',
  leadership: 'Leadership',
  tech: 'Technology',
  mission: 'Mission',
}
